version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      REDIS_HOST: redis
    networks:
      - backend

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      API_URL: http://api:8080
    networks:
      - backend

  agent:
    build: ./agent
    depends_on:
      - api
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
    driver: bridge