apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-alerts
  namespace: monitoring
spec:
  groups:
  - name: example.rules
    rules:
    - alert: AgentDown
      expr: kube_pod_status_ready{condition="true", namespace="default", pod=~"agent-.*"} == 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Agent is down"
        description: "Agent pod is not ready for more than 1 minute"
