apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - secrets.yaml
  - cluster-issuer.yaml
  - argocd-ingress.yaml
  - argocd-app.yaml

images:
  - name: devops-admin-platform-ui
    newName: ghcr.io/justrunme/devops-admin-platform/ui
    newTag: 6c75da6b75357850ab3dcaaf1c6d43b6dad45639

  - name: devops-admin-platform-api
    newName: ghcr.io/justrunme/devops-admin-platform/api
    newTag: 6c75da6b75357850ab3dcaaf1c6d43b6dad45639

  - name: devops-admin-platform-agent
    newName: ghcr.io/justrunme/devops-admin-platform/agent
    newTag: 6c75da6b75357850ab3dcaaf1c6d43b6dad45639
