apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - secrets.yaml
  - cluster-issuer.yaml
  - argocd-ingress.yaml
  - argocd-app.yaml

images:
  - name: devops-admin-platform-ui
    newName: ghcr.io/${{ github.repository }}/ui
    newTag: 89c5195b37fbe143e6305c49c7150ba62f5cb183

  - name: devops-admin-platform-api
    newName: ghcr.io/${{ github.repository }}/api
    newTag: 89c5195b37fbe143e6305c49c7150ba62f5cb183

  - name: devops-admin-platform-agent
    newName: ghcr.io/${{ github.repository }}/agent
    newTag: 89c5195b37fbe143e6305c49c7150ba62f5cb183