apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - secrets.yaml
  - cluster-issuer.yaml
  - argocd-ingress.yaml
  - argocd-app.yaml

images:
  - name: devops-admin-platform-ui
    newName: ghcr.io/justrunme/devops-admin-platform/ui
    newTag: bcca00daa1e960dc4ced1000a898304a1e73f0eb

  - name: devops-admin-platform-api
    newName: ghcr.io/justrunme/devops-admin-platform/api
    newTag: bcca00daa1e960dc4ced1000a898304a1e73f0eb

  - name: devops-admin-platform-agent
    newName: ghcr.io/justrunme/devops-admin-platform/agent
    newTag: bcca00daa1e960dc4ced1000a898304a1e73f0eb
