apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  postgres-password: secret
  database_url: postgres://app:secret@postgres-service:5432/app?sslmode=disable
  redis_url: redis://redis-service:6379