image:
  repository: ghcr.io/justrunme/devops-admin-platform/ui
  tag: "6c75da6"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: devops.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: ""