image:
  repository: ghcr.io/justrunme/devops-admin-platform/ui
  tag: 65a980958ccd77bf62bc5fee16764811b3507d5d

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: devops.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: ""