image:
  repository: ghcr.io/justrunme/devops-admin-platform/ui
  tag: dd8946707cc8f54a708532259f00bb8d11af9511

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: devops.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: ""