image:
  repository: ghcr.io/justrunme/devops-admin-platform/ui
  tag: 0731cba15825034ed7f8542838ff441a896a1b82

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: devops.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: ""