image:
  repository: ghcr.io/justrunme/devops-admin-platform/ui
  tag: 4d5c5f136db07c31dec4accc3a5b47d39929cfc5

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: devops.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: ""