image:
  repository: ghcr.io/justrunme/devops-admin-platform/ui
  tag: 4a5893c3ee50b0b11c62aef6f4c6fbd0aa6a9734

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: devops.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: ""