image:
  repository: ghcr.io/justrunme/devops-admin-platform/api
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: api.localhost
      paths:
        - /
