image:
  repository: ghcr.io/justrunme/devops-admin-platform/api
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: api.localhost
      paths:
        - path: /
          pathType: Prefix

database:
  url: postgres://app:secret@postgres-service:5432/app?sslmode=disable

redis:
  url: redis://redis-service:6379
