image:
  repository: ghcr.io/justrunme/devops-admin-platform/api
  tag: a177fecb1b770d04fe6e058cb4c79bea76e4adbe
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: api.localhost
      paths:
        - path: /
          pathType: Prefix

database:
  url: postgres://app:secret@postgres-service:5432/app?sslmode=disable

redis:
  url: redis://:supersecurepassword@redis-master:6379

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
