apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patch:
  - target:
      kind: Deployment
      name: api-deployment
    patch:
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: ui-deployment
    patch:
      - op: replace
        path: /spec/replicas
        value: 3
