name: Build & Push Docker Images + Update Kustomization

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract short SHA
      id: extract_sha
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push API
      run: |
        docker build -t ghcr.io/${{ github.repository }}/api:latest -t ghcr.io/${{ github.repository }}/api:${{ steps.extract_sha.outputs.short_sha }} ./api
        docker push ghcr.io/${{ github.repository }}/api:latest
        docker push ghcr.io/${{ github.repository }}/api:${{ steps.extract_sha.outputs.short_sha }}

    - name: Build and push UI
      run: |
        docker build -t ghcr.io/${{ github.repository }}/ui:latest -t ghcr.io/${{ github.repository }}/ui:${{ steps.extract_sha.outputs.short_sha }} ./ui
        docker push ghcr.io/${{ github.repository }}/ui:latest
        docker push ghcr.io/${{ github.repository }}/ui:${{ steps.extract_sha.outputs.short_sha }}

    - name: Build and push Agent
      run: |
        docker build -t ghcr.io/${{ github.repository }}/agent:latest -t ghcr.io/${{ github.repository }}/agent:${{ steps.extract_sha.outputs.short_sha }} ./agent
        docker push ghcr.io/${{ github.repository }}/agent:latest
        docker push ghcr.io/${{ github.repository }}/agent:${{ steps.extract_sha.outputs.short_sha }}

    - name: Update kustomization.yaml tags
      run: |
        sed -i "/name: devops-admin-platform-ui/,/newTag:/s/newTag: .*/newTag: ${{ steps.extract_sha.outputs.short_sha }}/" infra/k8s/base/kustomization.yaml
        sed -i "/name: devops-admin-platform-api/,/newTag:/s/newTag: .*/newTag: ${{ steps.extract_sha.outputs.short_sha }}/" infra/k8s/base/kustomization.yaml
        sed -i "/name: devops-admin-platform-agent/,/newTag:/s/newTag: .*/newTag: ${{ steps.extract_sha.outputs.short_sha }}/" infra/k8s/base/kustomization.yaml

    - name: Update values.yaml image tags
      run: |
        sed -i "s|tag: .*|tag: ${{ steps.extract_sha.outputs.short_sha }}|" charts/api/values.yaml
        sed -i "s|tag: .*|tag: ${{ steps.extract_sha.outputs.short_sha }}|" charts/ui/values.yaml
        sed -i "s|tag: .*|tag: ${{ steps.extract_sha.outputs.short_sha }}|" charts/agent/values.yaml

    - name: Commit and push if changes exist
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add charts/*/values.yaml infra/k8s/base/kustomization.yaml

        if git diff --cached --quiet; then
          echo "✅ Nothing to commit"
        else
          git commit -m "ci: update image tags to ${{ steps.extract_sha.outputs.short_sha }}"
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}