name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    env:
      REGISTRY: ghcr.io
      SHORT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #  Build & push all images
      - name: Build & Push Docker Images
        run: |
          for component in ui api agent; do
            docker build -t $REGISTRY/${{ github.repository }}/$component:$SHORT_SHA ./$component
            docker tag $REGISTRY/${{ github.repository }}/$component:$SHORT_SHA $REGISTRY/${{ github.repository }}/$component:latest
            docker push $REGISTRY/${{ github.repository }}/$component:$SHORT_SHA
            docker push $REGISTRY/${{ github.repository }}/$component:latest
          done

      #  Update image tags in values.yaml and kustomization.yaml
      - name: Update image tags
        run: |
          # Update Helm chart values.yaml for each component
          for chart in charts/ui charts/api charts/agent; do
            sed -i "s|tag: .*|tag: ${SHORT_SHA}|" $chart/values.yaml
          done

          # Update kustomization.yaml (image patches)
          sed -i "/name: devops-admin-platform-ui/,/newTag:/s/newTag: .*/newTag: ${SHORT_SHA}/" infra/k8s/base/kustomization.yaml
          sed -i "/name: devops-admin-platform-api/,/newTag:/s/newTag: .*/newTag: ${SHORT_SHA}/" infra/k8s/base/kustomization.yaml
          sed -i "/name: devops-admin-platform-agent/,/newTag:/s/newTag: .*/newTag: ${SHORT_SHA}/" infra/k8s/base/kustomization.yaml

      # ✅ Commit and push only if there are changes
      - name: Commit & Push updated tags
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/*/values.yaml infra/k8s/base/kustomization.yaml || true

          if git diff --cached --quiet; then
            echo "✅ No changes — nothing to commit."
          else
            git commit -m "ci: update image tags to ${SHORT_SHA}"
            git pull --rebase --autostash
            git push origin main
          fi