name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push UI image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/ui:${SHORT_SHA} ./ui
          docker tag ghcr.io/${{ github.repository }}/ui:${SHORT_SHA} ghcr.io/${{ github.repository }}/ui:latest
          docker push ghcr.io/${{ github.repository }}/ui:${SHORT_SHA}
          docker push ghcr.io/${{ github.repository }}/ui:latest

      - name: Build and push API image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/api:${SHORT_SHA} ./api
          docker tag ghcr.io/${{ github.repository }}/api:${SHORT_SHA} ghcr.io/${{ github.repository }}/api:latest
          docker push ghcr.io/${{ github.repository }}/api:${SHORT_SHA}
          docker push ghcr.io/${{ github.repository }}/api:latest

      - name: Build and push Agent image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/agent:${SHORT_SHA} ./agent
          docker tag ghcr.io/${{ github.repository }}/agent:${SHORT_SHA} ghcr.io/${{ github.repository }}/agent:latest
          docker push ghcr.io/${{ github.repository }}/agent:${SHORT_SHA}
          docker push ghcr.io/${{ github.repository }}/agent:latest

      - name: Update image tags in values.yaml and kustomization.yaml
        run: |
          sed -i "s|newTag: .*|newTag: ${SHORT_SHA}|g" infra/k8s/base/kustomization.yaml
          sed -i "s|tag: .*|tag: ${SHORT_SHA}|g" charts/ui/values.yaml
          sed -i "s|tag: .*|tag: ${SHORT_SHA}|g" charts/api/values.yaml
          sed -i "s|tag: .*|tag: ${SHORT_SHA}|g" charts/agent/values.yaml

      - name: Commit and push updated tags
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add charts/*/values.yaml infra/k8s/base/kustomization.yaml || true

          if git diff --cached --quiet; then
            echo "✅ No changes — nothing to commit."
          else
            git commit -m "ci: update image tags to ${SHORT_SHA}"
            git pull --rebase
            git push origin main
          fi